[package]
name = "woodns"
version = "2.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bollard = "0.19.1"
tokio = { version = "1.46.1", features = ["full"] }
trust-dns-proto = "0.23.2"
futures-util = "0.3"
log = "0.4.27"